import SKUImage from '../assets/images/SKUImage.png';
export const skuMockData = {
  id: 1234567,
  price: 6.99,
  name: 'Premium Stacking Sweater Bin Clear',
  description: 'Premium Stacking Sweater Bin Clear  12" x 14" x 8" h',
  longDescription: 'OXO 0.2 qt. Mini Square POP Container',
  skuType: 'B',
  keywords: null,
  sites: null,
  startDate: '2021-08-17T15:47:52.000+00:00',
  endDate: null,
  sortOrder: null,
  sourceUpdatedAt: null,
  status: 'A',
  upc: null,
  barcode: null,
  unitForSale: null,
  attribute: [
    {
      id: 'COUNTRY_OF_ORIGIN',
      name: 'US',
      type: null,
      description: null,
      order: null,
      group: null,
      isMandatory: null,
      metadata: null,
      values: null,
    },
    {
      id: 'COUNTRY_OF_ORIGIN_DESC',
      name: 'United States',
      type: null,
      description: null,
      order: null,
      group: null,
      isMandatory: null,
      metadata: null,
      values: null,
    },
    {
      id: 'NORETAIL',
      name: null,
      type: null,
      description: null,
      order: null,
      group: null,
      isMandatory: null,
      metadata: null,
      values: null,
    },
    {
      id: 'WEB_CATEGORIES',
      name: '2,4,22,153,62519,62589,71232,71921,81246,90767,90777,90898,90900,90972,91245,91265,91437,91441',
      type: null,
      description: null,
      order: null,
      group: null,
      isMandatory: null,
      metadata: null,
      values: null,
    },
    {
      id: 'YESWRAPPABLE',
      name: null,
      type: null,
      description: null,
      order: null,
      group: null,
      isMandatory: null,
      metadata: null,
      values: null,
    },
  ],
  offerings: [],
  dimension: {
    length: 12.0,
    width: null,
    height: 8.0,
    weight: 1.0,
    sizeUom: null,
    weightUom: null,
  },
  classMapping: {
    className: 'Bins',
    subClass: 'Plastic',
    department: 'CLOSET',
  },
  mediaList: [
    {
      id: null,
      name: 'SKU_SMALL_IMAGE',
      url: SKUImage,
      mediaType: null,
      primaryReferenceAssetId: null,
      primaryRreferenceAssetType: null,
      secondaryReferenceAssetId: null,
      mimeType: null,
      size: null,
      fileExtension: null,
      sortOrder: null,
      keywords: null,
      applicableChannels: null,
      mediaText: null,
      smallMediaText: null,
      largeMediaText: null,
      mediumMediaText: null,
      xlMediaText: null,
      thumbnailMediaText: null,
      mediaProviderId: null,
      mediaProvider: null,
      getsecondaryRreferenceAssetType: null,
    },
    {
      id: null,
      name: 'SKU_IMAGE',
      url: '/catalogimages/265759/4060PremiumStackingSweaterBinV2_600.jpg',
      mediaType: null,
      primaryReferenceAssetId: null,
      primaryRreferenceAssetType: null,
      secondaryReferenceAssetId: null,
      mimeType: null,
      size: null,
      fileExtension: null,
      sortOrder: null,
      keywords: null,
      applicableChannels: null,
      mediaText: null,
      smallMediaText: null,
      largeMediaText: null,
      mediumMediaText: null,
      xlMediaText: null,
      thumbnailMediaText: null,
      mediaProviderId: null,
      mediaProvider: null,
      getsecondaryRreferenceAssetType: null,
    },
  ],
  linkedSkus: null,
  bundledSKUs: null,
  linkedProducts: null,
  isPublished: null,
  sellingChannels: null,
  productTemplate: null,
  multiTierBadges: null,
  isActive: true,
  shippingDimension: null,
  collectionIds: null,
};

export const skuAvailability = {
  requestStoreNumber: '5',
  inventoryEstimates: [
    {
      skuNumber: '4010',
      fulfillmentStoreNumber: '5',
      requestedQty: 10100,
      earliestAvailabilityDateForEntireQty: null,
      qtyAvailableAtStore: 35,
      storeQtyAvailabilityDate: '2019-06-21',
      qtyAvailableInDc: 6301,
      dcQtyAvailabilityDate: '2019-07-04',
      dcPoQtyAvailabilityDate: null,
      backordered: 'true',
    },
    {
      skuNumber: '4010',
      fulfillmentStoreNumber: '23',
      requestedQty: 10100,
      earliestAvailabilityDateForEntireQty: null,
      qtyAvailableAtStore: 35,
      storeQtyAvailabilityDate: '2019-06-21',
      qtyAvailableInDc: 6301,
      dcQtyAvailabilityDate: '2019-07-04',
      dcPoQtyAvailabilityDate: null,
      backordered: 'true',
    },
    {
      skuNumber: '4020',
      fulfillmentStoreNumber: '5',
      requestedQty: 7000,
      earliestAvailabilityDateForEntireQty: '2019-09-04',
      qtyAvailableAtStore: 100,
      storeQtyAvailabilityDate: '2019-06-21',
      qtyAvailableInDc: 6000,
      dcQtyAvailabilityDate: '2019-07-04',
      dcPoQtyAvailabilityDate: '2019-09-04',
      poQtyAvailable: '500',
    },
    {
      skuNumber: '4020',
      fulfillmentStoreNumber: '23',
      requestedQty: 7000,
      earliestAvailabilityDateForEntireQty: '2019-09-04',
      qtyAvailableAtStore: 100,
      storeQtyAvailabilityDate: '2019-06-21',
      qtyAvailableInDc: 6000,
      dcQtyAvailabilityDate: '2019-07-04',
      dcPoQtyAvailabilityDate: '2019-09-04',
      poQtyAvailable: '500',
    },
  ],
};
