export const skuDetailsResponse = {
  id: 10069202,
  defaultProductId: 11003771,
  name: 'Mercer Entryway Storage Bench Rustic Driftwood',
  description:
    'Mercer Entryway Storage Bench Rustic Driftwood  33-3/4" x 17-1/2" x 20-5/8" h',
  longDescription:
    'Mercer Entryway Storage Bench Rustic Driftwood  33-3/4" x 17-1/2" x 20-5/8" h',
  skuType: 'B',
  store: 899,
  color: 'Rustic Driftwood',
  skuPrices: {
    minRetailPrice: {
      amount: 249.99,
      currency: 'USD',
      zero: false,
    },
    maxRetailPrice: {
      amount: 249.99,
      currency: 'USD',
      zero: false,
    },
    minSalePrice: {
      amount: 249.99,
      currency: 'USD',
      zero: false,
    },
    maxSalePrice: {
      amount: 249.99,
      currency: 'USD',
      zero: false,
    },
    minSavings: {
      amount: 0.0,
      currency: 'USD',
      zero: true,
    },
    maxSavings: {
      amount: 0.0,
      currency: 'USD',
      zero: true,
    },
    minRetailPackage: false,
    maxRetailPackage: false,
    minSalePackage: false,
    maxSalePackage: false,
    minPercentOff: 0,
    maxPercentOff: 0,
    onSale: false,
    allOnSale: false,
  },
  startDate: '2021-08-17T21:17:52.000+00:00',
  status: 'A',
  attribute: [
    {
      id: 'COUNTRY_OF_ORIGIN',
      name: 'CN',
    },
    {
      id: 'COUNTRY_OF_ORIGIN_DESC',
      name: 'China',
    },
    {
      id: 'NORETAIL',
    },
    {
      id: 'WEB_CATEGORIES',
      name: '2,4,22,153,247,13376,62519,62589,80411,81213,81811,90395,90510,90545,90659,90672,90680,90767,90773,90973',
    },
  ],
  dimension: {
    length: 33.75,
    width: 17.5,
    height: 20.625,
    weight: 0.0,
  },
  dimensionDescription: '33-3/4" x 17-1/2" x 20-5/8" h',
  classMapping: {
    name: 'Entry',
    subClass: 'Benches',
    department: 'HOOKS',
  },
  mediaList: [
    {
      name: 'amazon',
      url: '/catalogimages/345259/SH_16_Mercer_Bench_V1_R070717_1200.jpg',
      mediaType: 'image',
    },
    {
      name: 'small',
      url: '/catalogimages/345260/SH_16_Mercer_Bench_V1_R070717_1200.jpg',
      mediaType: 'image',
    },
    {
      name: 'large',
      url: '/catalogimages/345258/SH_16_Mercer_Bench_V1_R070717_1200.jpg',
      mediaType: 'image',
    },
    {
      name: 'thumb',
      url: '/catalogimages/345261/SH_16_Mercer_Bench_V1_R070717_1200.jpg',
      mediaType: 'image',
    },
    {
      name: 'xtra_large',
      url: '/catalogimages/345254/SH_16_Mercer_Bench_V1_R070717_1200.jpg',
      mediaType: 'image',
    },
  ],
  isActive: true,
};

export const popAccountDetails = {
  customers: [
    {
      customerId: 'WEB470966052',
      evId: 'QUJqN0lUZXhUZGpHNE9DdjZtYm0wcTBmTWdmQ3NXRjF5Zg',
      emailAddress: 'bmregan@containerstore.com',
      updatedAt: '2016-02-18T02:25:09.000-06:00',
      firstName: 'Brian',
      lastName: 'Regan',
      phones: [
        {
          id: '11690690',
          phonePreferences: [
            {
              type: 'DEFAULT',
            },
          ],
          digits: '8172913409',
          label: 'cell',
          extension: null,
          note: null,
        },
        {
          id: '12078474',
          phonePreferences: [],
          digits: '8172949502',
          label: 'home',
          extension: null,
          note: null,
        },
      ],
      addresses: [
        {
          id: '8436363',
          addressPreferences: [
            {
              type: 'DEFAULT',
            },
          ],
          label: null,
          firstName: 'Brian',
          lastName: 'Regan',
          companyName: null,
          address1: '8401 Southern Prairie Dr',
          address2: null,
          city: 'Fort Worth',
          state: 'TX',
          postalCode: '76123-2907',
          country: 'US',
          business: false,
          note: null,
        },
        {
          id: '8698119',
          addressPreferences: [],
          label: null,
          firstName: 'Brian',
          lastName: 'Regan',
          companyName: null,
          address1: '1551 Oak Lawn Ave',
          address2: 'Apt 132',
          city: 'Dallas',
          state: 'TX',
          postalCode: '75207-3659',
          country: 'US',
          business: false,
          note: null,
        },
        {
          id: '8243108',
          addressPreferences: [],
          label: 'Billing',
          firstName: 'Brian',
          lastName: 'Regan',
          companyName: null,
          address1: '1551 Oak Lawn Ave',
          address2: 'Apt 132',
          city: 'Dallas',
          state: 'TX',
          postalCode: '75207',
          country: 'US',
          business: false,
          note: null,
        },
        {
          id: '8869277',
          addressPreferences: [],
          label: 'Home',
          firstName: 'Brian',
          lastName: 'Regan',
          companyName: null,
          address1: '500 Freeport Pkwy',
          address2: null,
          city: 'Coppell',
          state: 'TX',
          postalCode: '75019',
          country: 'US',
          business: false,
          note: null,
        },
        {
          id: '9282914',
          addressPreferences: [
            {
              type: 'MARKETING',
            },
          ],
          label: null,
          firstName: 'Brian',
          lastName: 'Regan',
          companyName: null,
          address1: '710 S. Sepulveda Blvd',
          address2: null,
          city: 'El Segundo',
          state: 'CA',
          postalCode: '90245',
          country: 'US',
          business: false,
          note: null,
        },
      ],
      recentStores: [16, 61, 22],
      emailFrequencyPreference: 'NONE',
      birthday: null,
      popMember: true,
      optedInToEmail: false,
      popTermsAcceptedAt: null,
      interestedInBlog: false,
      businessSales: false,
      webCustomer: true,
      enrolledInTradeProgram: false,
      webCustomerId: '1',
      popAccount: {
        popId: '4000000028',
        popEnrollmentDateTime: '2013-07-11T10:45:28.000-05:00',
        termsAcceptedAt: null,
      },
      storeInteractions: [
        {
          type: 'CREATED_CUSTOMER_ACCOUNT',
          storeNumber: 16,
          interactionDateTime: '2013-01-03T00:00:00.000-06:00',
        },
        {
          type: 'CREATED_CUSTOMER_ACCOUNT',
          storeNumber: 61,
          interactionDateTime: '2013-07-11T00:00:00.000-05:00',
        },
        {
          type: 'CREATED_CUSTOMER_ACCOUNT',
          storeNumber: 22,
          interactionDateTime: '2012-04-21T00:00:00.000-05:00',
        },
      ],
      createDateTime: '2016-02-18T02:25:09.000-06:00',
      containedHome: false,
    },
    {
      customerId: 'C9900000034730542',
      evId: 'QUJTOWNWK0NYZlNKTTFJWGN5OS92d1dyVzF4eGVIR1o5ZzYxN0VoQllKeTZVPQ',
      emailAddress: 'mptest999@yopmail.com',
      updatedAt: '2021-11-12T06:55:57.288-06:00',
      firstName: 'Test',
      lastName: 'test',
      phones: [
        {
          id: '29575116',
          phonePreferences: [
            {
              type: 'DEFAULT',
            },
          ],
          digits: '8172949502',
          label: null,
          extension: null,
          note: null,
        },
      ],
      addresses: [],
      recentStores: [899],
      emailFrequencyPreference: 'ALL',
      birthday: {
        day: 1,
        month: 1,
      },
      popMember: true,
      optedInToEmail: true,
      popTermsAcceptedAt: '2021-11-12T06:55:57.000-06:00',
      interestedInBlog: false,
      businessSales: false,
      webCustomer: true,
      enrolledInTradeProgram: false,
      webCustomerId: '1',
      popAccount: {
        popId: '900000034730542',
        popEnrollmentDateTime: '2021-11-12T06:55:57.000-06:00',
        termsAcceptedAt: '2021-11-12T06:55:57.000-06:00',
      },
      storeInteractions: [
        {
          type: 'CREATED_CUSTOMER_ACCOUNT',
          storeNumber: 899,
          interactionDateTime: '2021-11-12T06:55:56.000-06:00',
        },
      ],
      createDateTime: '2021-11-12T06:55:57.288-06:00',
      containedHome: false,
    },
  ],
};
