export const skuAvailability = {
  requestStoreNumber: '5',
  inventoryEstimates: [
    {
      skuNumber: '4010',
      fulfillmentStoreNumber: '5',
      requestedQty: 10100,
      earliestAvailabilityDateForEntireQty: null,
      qtyAvailableAtStore: 35,
      storeQtyAvailabilityDate: '2019-06-21',
      qtyAvailableInDc: 6301,
      dcQtyAvailabilityDate: '2019-07-04',
      dcPoQtyAvailabilityDate: null,
      backordered: 'true',
    },
    {
      skuNumber: '4010',
      fulfillmentStoreNumber: '23',
      requestedQty: 10100,
      earliestAvailabilityDateForEntireQty: null,
      qtyAvailableAtStore: 35,
      storeQtyAvailabilityDate: '2019-06-21',
      qtyAvailableInDc: 6301,
      dcQtyAvailabilityDate: '2019-07-04',
      dcPoQtyAvailabilityDate: null,
      backordered: 'true',
    },
    {
      skuNumber: '4020',
      fulfillmentStoreNumber: '5',
      requestedQty: 7000,
      earliestAvailabilityDateForEntireQty: '2019-09-04',
      qtyAvailableAtStore: 100,
      storeQtyAvailabilityDate: '2019-06-21',
      qtyAvailableInDc: 6000,
      dcQtyAvailabilityDate: '2019-07-04',
      dcPoQtyAvailabilityDate: '2019-09-04',
      poQtyAvailable: '500',
    },
    {
      skuNumber: '4020',
      fulfillmentStoreNumber: '23',
      requestedQty: 7000,
      earliestAvailabilityDateForEntireQty: '2019-09-04',
      qtyAvailableAtStore: 100,
      storeQtyAvailabilityDate: '2019-06-21',
      qtyAvailableInDc: 6000,
      dcQtyAvailabilityDate: '2019-07-04',
      dcPoQtyAvailabilityDate: '2019-09-04',
      poQtyAvailable: '500',
    },
  ],
};

export const questions = {
  name: 'questions',
  paging: {
    total_results: 3,
    pages_total: 1,
    page_size: 10,
    current_page_number: 1,
  },
  results: [
    {
      ugc_id: 380507831,
      question_id: '8123156',
      details: {
        nickname: 'migb',
        created_date: 1629812604000,
        text: 'How do you clean these before reusing?',
        location: 'Ashtabula, OH',
        product_page_id: '11014345',
        is_seeded: false,
      },
      answer: [
        {
          ugc_id: 380510586,
          answer_id: '7169235',
          details: {
            nickname: 'beneel',
            location: 'USA',
            text: 'These bags can be cleaned using a dishwasher or by hand-washing.',
            is_verified: true,
            is_expert: false,
            author_type: 'COMMUNITY',
            created_date: 1631382272000,
          },
          metrics: {
            helpful_votes: 0,
            not_helpful_votes: 0,
          },
        },
        {
          ugc_id: 380510586,
          answer_id: '7169235',
          details: {
            nickname: 'beneel',
            location: 'USA',
            text: 'These bags can be cleaned using a dishwasher or by hand-washing.',
            is_verified: true,
            is_expert: false,
            author_type: 'COMMUNITY',
            created_date: 1631382272000,
          },
          metrics: {
            helpful_votes: 0,
            not_helpful_votes: 0,
          },
        },
        {
          ugc_id: 380510586,
          answer_id: '7169235',
          details: {
            nickname: 'beneel',
            location: 'USA',
            text: 'These bags can be cleaned using a dishwasher or by hand-washing.',
            is_verified: true,
            is_expert: false,
            author_type: 'COMMUNITY',
            created_date: 1631382272000,
          },
          metrics: {
            helpful_votes: 0,
            not_helpful_votes: 0,
          },
        },
        {
          ugc_id: 380510586,
          answer_id: '7169235',
          details: {
            nickname: 'beneel',
            location: 'USA',
            text: 'These bags can be cleaned using a dishwasher or by hand-washing.',
            is_verified: true,
            is_expert: false,
            author_type: 'COMMUNITY',
            created_date: 1631382272000,
          },
          metrics: {
            helpful_votes: 0,
            not_helpful_votes: 0,
          },
        },
        {
          ugc_id: 380510586,
          answer_id: '7169235',
          details: {
            nickname: 'beneel',
            location: 'USA',
            text: 'These bags can be cleaned using a dishwasher or by hand-washing.',
            is_verified: true,
            is_expert: false,
            author_type: 'COMMUNITY',
            created_date: 1631382272000,
          },
          metrics: {
            helpful_votes: 0,
            not_helpful_votes: 0,
          },
        },
      ],
      answer_count: 1,
    },
    {
      ugc_id: 380507831,
      question_id: '8123156',
      details: {
        nickname: 'migb',
        created_date: 1629812604000,
        text: 'How do you clean these before reusing?',
        location: 'Ashtabula, OH',
        product_page_id: '11014345',
        is_seeded: false,
      },
      answer: [
        {
          ugc_id: 380510586,
          answer_id: '7169235',
          details: {
            nickname: 'beneel',
            location: 'USA',
            text: 'These bags can be cleaned using a dishwasher or by hand-washing.',
            is_verified: true,
            is_expert: false,
            author_type: 'COMMUNITY',
            created_date: 1631382272000,
          },
          metrics: {
            helpful_votes: 0,
            not_helpful_votes: 0,
          },
        },
      ],
      answer_count: 1,
    },
    {
      ugc_id: 380507831,
      question_id: '8123156',
      details: {
        nickname: 'migb',
        created_date: 1629812604000,
        text: 'How do you clean these before reusing?',
        location: 'Ashtabula, OH',
        product_page_id: '11014345',
        is_seeded: false,
      },
      answer: [
        {
          ugc_id: 380510586,
          answer_id: '7169235',
          details: {
            nickname: 'beneel',
            location: 'USA',
            text: 'These bags can be cleaned using a dishwasher or by hand-washing.',
            is_verified: true,
            is_expert: false,
            author_type: 'COMMUNITY',
            created_date: 1631382272000,
          },
          metrics: {
            helpful_votes: 0,
            not_helpful_votes: 0,
          },
        },
      ],
      answer_count: 1,
    },
    {
      ugc_id: 380507831,
      question_id: '8123156',
      details: {
        nickname: 'migb',
        created_date: 1629812604000,
        text: 'How do you clean these before reusing?',
        location: 'Ashtabula, OH',
        product_page_id: '11014345',
        is_seeded: false,
      },
      answer: [
        {
          ugc_id: 380510586,
          answer_id: '7169235',
          details: {
            nickname: 'beneel',
            location: 'USA',
            text: 'These bags can be cleaned using a dishwasher or by hand-washing.',
            is_verified: true,
            is_expert: false,
            author_type: 'COMMUNITY',
            created_date: 1631382272000,
          },
          metrics: {
            helpful_votes: 0,
            not_helpful_votes: 0,
          },
        },
      ],
      answer_count: 1,
    },
    {
      ugc_id: 380507831,
      question_id: '8123156',
      details: {
        nickname: 'migb',
        created_date: 1629812604000,
        text: 'How do you clean these before reusing?',
        location: 'Ashtabula, OH',
        product_page_id: '11014345',
        is_seeded: false,
      },
      answer: [
        {
          ugc_id: 380510586,
          answer_id: '7169235',
          details: {
            nickname: 'beneel',
            location: 'USA',
            text: 'These bags can be cleaned using a dishwasher or by hand-washing.',
            is_verified: true,
            is_expert: false,
            author_type: 'COMMUNITY',
            created_date: 1631382272000,
          },
          metrics: {
            helpful_votes: 0,
            not_helpful_votes: 0,
          },
        },
      ],
      answer_count: 1,
    },
    {
      ugc_id: 380507831,
      question_id: '8123156',
      details: {
        nickname: 'migb',
        created_date: 1629812604000,
        text: 'How do you clean these before reusing?',
        location: 'Ashtabula, OH',
        product_page_id: '11014345',
        is_seeded: false,
      },
      answer: [
        {
          ugc_id: 380510586,
          answer_id: '7169235',
          details: {
            nickname: 'beneel',
            location: 'USA',
            text: 'These bags can be cleaned using a dishwasher or by hand-washing.',
            is_verified: true,
            is_expert: false,
            author_type: 'COMMUNITY',
            created_date: 1631382272000,
          },
          metrics: {
            helpful_votes: 0,
            not_helpful_votes: 0,
          },
        },
      ],
      answer_count: 1,
    },
    {
      ugc_id: 380507831,
      question_id: '8123156',
      details: {
        nickname: 'migb',
        created_date: 1629812604000,
        text: 'How do you clean these before reusing?',
        location: 'Ashtabula, OH',
        product_page_id: '11014345',
        is_seeded: false,
      },
      answer: [
        {
          ugc_id: 380510586,
          answer_id: '7169235',
          details: {
            nickname: 'beneel',
            location: 'USA',
            text: 'These bags can be cleaned using a dishwasher or by hand-washing.',
            is_verified: true,
            is_expert: false,
            author_type: 'COMMUNITY',
            created_date: 1631382272000,
          },
          metrics: {
            helpful_votes: 0,
            not_helpful_votes: 0,
          },
        },
      ],
      answer_count: 1,
    },
    {
      ugc_id: 380507831,
      question_id: '8123156',
      details: {
        nickname: 'migb',
        created_date: 1629812604000,
        text: 'How do you clean these before reusing?',
        location: 'Ashtabula, OH',
        product_page_id: '11014345',
        is_seeded: false,
      },
      answer: [
        {
          ugc_id: 380510586,
          answer_id: '7169235',
          details: {
            nickname: 'beneel',
            location: 'USA',
            text: 'These bags can be cleaned using a dishwasher or by hand-washing.',
            is_verified: true,
            is_expert: false,
            author_type: 'COMMUNITY',
            created_date: 1631382272000,
          },
          metrics: {
            helpful_votes: 0,
            not_helpful_votes: 0,
          },
        },
      ],
      answer_count: 1,
    },
    {
      ugc_id: 380507831,
      question_id: '8123156',
      details: {
        nickname: 'migb',
        created_date: 1629812604000,
        text: 'How do you clean these before reusing?',
        location: 'Ashtabula, OH',
        product_page_id: '11014345',
        is_seeded: false,
      },
      answer: [
        {
          ugc_id: 380510586,
          answer_id: '7169235',
          details: {
            nickname: 'beneel',
            location: 'USA',
            text: 'These bags can be cleaned using a dishwasher or by hand-washing.',
            is_verified: true,
            is_expert: false,
            author_type: 'COMMUNITY',
            created_date: 1631382272000,
          },
          metrics: {
            helpful_votes: 0,
            not_helpful_votes: 0,
          },
        },
      ],
      answer_count: 1,
    },
    {
      ugc_id: 380507831,
      question_id: '8123156',
      details: {
        nickname: 'migb',
        created_date: 1629812604000,
        text: 'How do you clean these before reusing?',
        location: 'Ashtabula, OH',
        product_page_id: '11014345',
        is_seeded: false,
      },
      answer: [
        {
          ugc_id: 380510586,
          answer_id: '7169235',
          details: {
            nickname: 'beneel',
            location: 'USA',
            text: 'These bags can be cleaned using a dishwasher or by hand-washing.',
            is_verified: true,
            is_expert: false,
            author_type: 'COMMUNITY',
            created_date: 1631382272000,
          },
          metrics: {
            helpful_votes: 0,
            not_helpful_votes: 0,
          },
        },
      ],
      answer_count: 1,
    },
    {
      ugc_id: 380507831,
      question_id: '8123156',
      details: {
        nickname: 'migb',
        created_date: 1629812604000,
        text: 'How do you clean these before reusing?',
        location: 'Ashtabula, OH',
        product_page_id: '11014345',
        is_seeded: false,
      },
      answer: [
        {
          ugc_id: 380510586,
          answer_id: '7169235',
          details: {
            nickname: 'beneel',
            location: 'USA',
            text: 'These bags can be cleaned using a dishwasher or by hand-washing.',
            is_verified: true,
            is_expert: false,
            author_type: 'COMMUNITY',
            created_date: 1631382272000,
          },
          metrics: {
            helpful_votes: 0,
            not_helpful_votes: 0,
          },
        },
      ],
      answer_count: 1,
    },
    {
      ugc_id: 380507831,
      question_id: '8123156',
      details: {
        nickname: 'migb',
        created_date: 1629812604000,
        text: 'How do you clean these before reusing?',
        location: 'Ashtabula, OH',
        product_page_id: '11014345',
        is_seeded: false,
      },
      answer: [
        {
          ugc_id: 380510586,
          answer_id: '7169235',
          details: {
            nickname: 'beneel',
            location: 'USA',
            text: 'These bags can be cleaned using a dishwasher or by hand-washing.',
            is_verified: true,
            is_expert: false,
            author_type: 'COMMUNITY',
            created_date: 1631382272000,
          },
          metrics: {
            helpful_votes: 0,
            not_helpful_votes: 0,
          },
        },
      ],
      answer_count: 1,
    },
    {
      ugc_id: 380507831,
      question_id: '8123156',
      details: {
        nickname: 'migb',
        created_date: 1629812604000,
        text: 'How do you clean these before reusing?',
        location: 'Ashtabula, OH',
        product_page_id: '11014345',
        is_seeded: false,
      },
      answer: [
        {
          ugc_id: 380510586,
          answer_id: '7169235',
          details: {
            nickname: 'beneel',
            location: 'USA',
            text: 'These bags can be cleaned using a dishwasher or by hand-washing.',
            is_verified: true,
            is_expert: false,
            author_type: 'COMMUNITY',
            created_date: 1631382272000,
          },
          metrics: {
            helpful_votes: 0,
            not_helpful_votes: 0,
          },
        },
      ],
      answer_count: 1,
    },
    {
      ugc_id: 380507831,
      question_id: '8123156',
      details: {
        nickname: 'migb',
        created_date: 1629812604000,
        text: 'How do you clean these before reusing?',
        location: 'Ashtabula, OH',
        product_page_id: '11014345',
        is_seeded: false,
      },
      answer: [
        {
          ugc_id: 380510586,
          answer_id: '7169235',
          details: {
            nickname: 'beneel',
            location: 'USA',
            text: 'These bags can be cleaned using a dishwasher or by hand-washing.',
            is_verified: true,
            is_expert: false,
            author_type: 'COMMUNITY',
            created_date: 1631382272000,
          },
          metrics: {
            helpful_votes: 0,
            not_helpful_votes: 0,
          },
        },
      ],
      answer_count: 1,
    },
    {
      ugc_id: 380507831,
      question_id: '8123156',
      details: {
        nickname: 'migb',
        created_date: 1629812604000,
        text: 'How do you clean these before reusing?',
        location: 'Ashtabula, OH',
        product_page_id: '11014345',
        is_seeded: false,
      },
      answer: [
        {
          ugc_id: 380510586,
          answer_id: '7169235',
          details: {
            nickname: 'beneel',
            location: 'USA',
            text: 'These bags can be cleaned using a dishwasher or by hand-washing.',
            is_verified: true,
            is_expert: false,
            author_type: 'COMMUNITY',
            created_date: 1631382272000,
          },
          metrics: {
            helpful_votes: 0,
            not_helpful_votes: 0,
          },
        },
      ],
      answer_count: 1,
    },
    {
      ugc_id: 380507831,
      question_id: '8123156',
      details: {
        nickname: 'migb',
        created_date: 1629812604000,
        text: 'How do you clean these before reusing?',
        location: 'Ashtabula, OH',
        product_page_id: '11014345',
        is_seeded: false,
      },
      answer: [
        {
          ugc_id: 380510586,
          answer_id: '7169235',
          details: {
            nickname: 'beneel',
            location: 'USA',
            text: 'These bags can be cleaned using a dishwasher or by hand-washing.',
            is_verified: true,
            is_expert: false,
            author_type: 'COMMUNITY',
            created_date: 1631382272000,
          },
          metrics: {
            helpful_votes: 0,
            not_helpful_votes: 0,
          },
        },
      ],
      answer_count: 1,
    },
    {
      ugc_id: 380507831,
      question_id: '8123156',
      details: {
        nickname: 'migb',
        created_date: 1629812604000,
        text: 'How do you clean these before reusing?',
        location: 'Ashtabula, OH',
        product_page_id: '11014345',
        is_seeded: false,
      },
      answer: [
        {
          ugc_id: 380510586,
          answer_id: '7169235',
          details: {
            nickname: 'beneel',
            location: 'USA',
            text: 'These bags can be cleaned using a dishwasher or by hand-washing.',
            is_verified: true,
            is_expert: false,
            author_type: 'COMMUNITY',
            created_date: 1631382272000,
          },
          metrics: {
            helpful_votes: 0,
            not_helpful_votes: 0,
          },
        },
      ],
      answer_count: 1,
    },
    {
      ugc_id: 380507831,
      question_id: '8123156',
      details: {
        nickname: 'migb',
        created_date: 1629812604000,
        text: 'How do you clean these before reusing?',
        location: 'Ashtabula, OH',
        product_page_id: '11014345',
        is_seeded: false,
      },
      answer: [
        {
          ugc_id: 380510586,
          answer_id: '7169235',
          details: {
            nickname: 'beneel',
            location: 'USA',
            text: 'These bags can be cleaned using a dishwasher or by hand-washing.',
            is_verified: true,
            is_expert: false,
            author_type: 'COMMUNITY',
            created_date: 1631382272000,
          },
          metrics: {
            helpful_votes: 0,
            not_helpful_votes: 0,
          },
        },
      ],
      answer_count: 1,
    },
    {
      ugc_id: 380507831,
      question_id: '8123156',
      details: {
        nickname: 'migb',
        created_date: 1629812604000,
        text: 'How do you clean these before reusing?',
        location: 'Ashtabula, OH',
        product_page_id: '11014345',
        is_seeded: false,
      },
      answer: [
        {
          ugc_id: 380510586,
          answer_id: '7169235',
          details: {
            nickname: 'beneel',
            location: 'USA',
            text: 'These bags can be cleaned using a dishwasher or by hand-washing.',
            is_verified: true,
            is_expert: false,
            author_type: 'COMMUNITY',
            created_date: 1631382272000,
          },
          metrics: {
            helpful_votes: 0,
            not_helpful_votes: 0,
          },
        },
      ],
      answer_count: 1,
    },
    {
      ugc_id: 380507831,
      question_id: '8123156',
      details: {
        nickname: 'migb',
        created_date: 1629812604000,
        text: 'How do you clean these before reusing?',
        location: 'Ashtabula, OH',
        product_page_id: '11014345',
        is_seeded: false,
      },
      answer: [
        {
          ugc_id: 380510586,
          answer_id: '7169235',
          details: {
            nickname: 'beneel',
            location: 'USA',
            text: 'These bags can be cleaned using a dishwasher or by hand-washing.',
            is_verified: true,
            is_expert: false,
            author_type: 'COMMUNITY',
            created_date: 1631382272000,
          },
          metrics: {
            helpful_votes: 0,
            not_helpful_votes: 0,
          },
        },
      ],
      answer_count: 1,
    },
    {
      ugc_id: 380507815,
      question_id: '8123164',
      details: {
        nickname: 'Tripespino',
        created_date: 1629751469000,
        text: 'Are these silicone containers easy to open? Wondering if a 7 year old child will be able to open these containers at school with no assistance? Thank you',
        location: 'Pacific Palisades, CA',
        product_page_id: '11014345',
        is_seeded: false,
      },
      answer: [
        {
          ugc_id: 380510580,
          answer_id: '7169241',
          details: {
            nickname: 'snzeigler',
            location: 'USA',
            text: 'Yes, very easy to open.',
            is_verified: true,
            is_expert: false,
            author_type: 'COMMUNITY',
            created_date: 1629814386000,
          },
          metrics: {
            helpful_votes: 0,
            not_helpful_votes: 0,
          },
        },
      ],
      answer_count: 1,
    },
    {
      ugc_id: 379197580,
      question_id: '8084195',
      details: {
        nickname: 'lcblue',
        created_date: 1617632895000,
        text: 'Are these actually created and produced in the USA or are they just assembled in the USA?',
        location: 'Virginia',
        product_page_id: '11014345',
        is_seeded: false,
      },
      answer: [
        {
          ugc_id: 379228256,
          answer_id: '7130273',
          details: {
            nickname: 'snzeigler',
            location: 'USA',
            text: 'The Zip Top Teal Reusable Silicone Containers Full Set of 8 have been created and produced in the USA. Thank you for your question!',
            is_verified: true,
            is_expert: false,
            author_type: 'COMMUNITY',
            created_date: 1617975730000,
          },
          metrics: {
            helpful_votes: 0,
            not_helpful_votes: 0,
          },
        },
      ],
      answer_count: 1,
    },
  ],
};
